Update trellis-deploy.yml

diff --git a/.github/workflows/trellis-deploy.yml b/.github/workflows/trellis-deploy.yml
--- a/.github/workflows/trellis-deploy.yml
+++ b/.github/workflows/trellis-deploy.yml
@@ -1,6 +1,7 @@
-# .github/workflows/trellis-deploy.yml
+# yamllint disable-line rule:document-start
 name: deploy
 
+# yamllint disable-line rule:truthy
 on:
   workflow_call:
     inputs:
@@ -47,22 +48,26 @@ on:
         required: true
       ANSIBLE_VAULT_PASSWORD:
         required: true
-      ZEROTIER_NETWORK_ID:
-        required: true
-      ZEROTIER_CENTRAL_TOKEN:
-        required: true
-      ZEROTIER_GATEWAY_IP:
-        required: true
       FONTAWESOME_NPM_AUTH_TOKEN:
         required: false
       ITINERIS_NPM_AUTH_TOKEN:
         required: false
+      ZEROTIER_CENTRAL_TOKEN:
+        required: true
+      ZEROTIER_GATEWAY_IP:
+        required: true
+      ZEROTIER_NETWORK_ID:
+        required: true
 
 jobs:
   deploy:
     name: "${{ inputs.TRELLIS_ENVIRONMENT }}"
     runs-on: ubuntu-latest
 
+    concurrency:
+      group: "${{ github.workflow }}-${{ github.ref_name }}"
+      cancel-in-progress: false
+    if: github.sha != vars.LAST_DEPLOY && github.actor != 'kodiakhq[bot]' && github.actor != 'dependabot[bot]' && !contains(github.event.head_commit.message, '[cd skip]')
     steps:
       - name: Checkout Trellis
         uses: actions/checkout@v4
@@ -71,12 +76,14 @@ jobs:
           path: trellis
           token: "${{ secrets.REPO_PAT }}"
 
-      - name: Get environment IP and port
+      - name: Get environment IP address
         run: |
-          HOST_IP=$(grep -Eo 'ansible_host=[0-9]{1,3}(\.[0-9]{1,3}){3}' "hosts/${{ inputs.TRELLIS_ENVIRONMENT }}" | sed 's/ansible_host=//')
-          KINSTA_PORT=$(grep -Eo 'ansible_port=[0-9]+' "hosts/${{ inputs.TRELLIS_ENVIRONMENT }}" | sed 's/ansible_port=//')
-          echo "HOST_IP=$HOST_IP" >> $GITHUB_ENV
-          echo "KINSTA_PORT=$KINSTA_PORT" >> $GITHUB_ENV
+          HOST_IP="$(grep -Po 'ansible_host=((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}' "hosts/${{ inputs.TRELLIS_ENVIRONMENT }}" | sed 's/ansible_host=//g')"
+          if [ -z "${HOST_IP}" ]; then
+            echo 'HOST_IP not found.'
+            exit 1
+          fi
+          echo "HOST_IP=${HOST_IP}" >> "${GITHUB_ENV}"
         working-directory: trellis
 
       - name: Install ZeroTier
@@ -85,7 +92,7 @@ jobs:
           network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
           auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
 
-      - name: Route Kinsta traffic through ZeroTier
+      - name: Route environment traffic through ZeroTier
         run: sudo ip route add "${HOST_IP}/32" via "${{ secrets.ZEROTIER_GATEWAY_IP }}"
 
       - name: Checkout Bedrock
@@ -99,14 +106,15 @@ jobs:
         with:
           node-version: "${{ inputs.NODE_VERSION }}"
           cache: yarn
+          # yamllint disable-line rule:line-length
           cache-dependency-path: bedrock/web/app/themes/${{ inputs.THEME_NAME }}/yarn.lock
         env:
+          # yamllint disable-line rule:line-length
           FONTAWESOME_NPM_AUTH_TOKEN: "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           ITINERIS_NPM_AUTH_TOKEN: ${{ secrets.ITINERIS_NPM_AUTH_TOKEN }}
 
-      - name: Add Trellis deploy key
-        uses: shimataro/ssh-key-action@v2
+      - uses: shimataro/ssh-key-action@v2
         with:
           key: "${{ secrets.TRELLIS_DEPLOY_SSH_PRIVATE_KEY }}"
           known_hosts: "${{ secrets.TRELLIS_DEPLOY_SSH_KNOWN_HOSTS }}"
@@ -124,12 +132,12 @@ jobs:
           version: "${{ inputs.TRELLIS_CLI_VERSION }}"
           repo-token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Deploy via Trellis
+      - name: Deploy
         working-directory: trellis
-        run: |
-          export KINSTA_PHP_PREPEND=''
-          trellis deploy --verbose --branch="${{ inputs.BEDROCK_DEPLOY_BRANCH }}" "${{ inputs.TRELLIS_ENVIRONMENT }}"
+        # yamllint disable-line rule:line-length
+        run: trellis deploy --verbose --branch="${{ inputs.BEDROCK_DEPLOY_BRANCH }}" "${{ inputs.TRELLIS_ENVIRONMENT }}"
         env:
+          # yamllint disable-line rule:line-length
           FONTAWESOME_NPM_AUTH_TOKEN: "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
           ITINERIS_NPM_AUTH_TOKEN: ${{ secrets.ITINERIS_NPM_AUTH_TOKEN }}
 
